[package]
name = "assignment_2"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.4"
plotters = { version = "0.3.1", features = ["bitmap_backend"] }
open = "3.2.0"
indicatif = "0.17.8"
rand = "0.8.5"
rfd = "0.15.0"
